name: Deploy to Dev/Staging

on:
  push:
    branches:
      - dev
      - staging

env:
  IMAGE_NAME: oranmz/app

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment variables
        id: env_vars
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
            echo "DOCKER_TAG=staging" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Copy and deploy to Azure VM
        run: |
          az vm run-command invoke \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_VM_NAME }} \
            --command-id RunShellScript \
            --scripts 'cd /app && \
                      docker compose --profile ${{ env.DEPLOY_ENV }} down -v && \
                      docker compose --profile ${{ env.DEPLOY_ENV }} pull && \
                      docker compose --profile ${{ env.DEPLOY_ENV }} up -d --force-recreate'
