name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  deploy-production:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.event == 'pull_request')
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Production VM
        run: |
          az vm run-command invoke \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_VM_NAME }} \
            --command-id RunShellScript \
            --scripts 'cd /home/ISadmin/app ; \
                      echo "Deploying to Production" ; \
                      docker-compose --profile prod down -v ; \
                      docker compose --profile prod pull ; \
                      docker compose --profile prod up -d --force-recreate'