name: Deploy to Production

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            oranmz/app:latest
            oranmz/app:${{ github.ref_name }}
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Production VM
        run: |
          # Use Azure CLI to execute deployment commands
          az vm run-command invoke \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_VM_NAME }} \
            --command-id RunShellScript \
            --scripts 'cd /home/ISadmin/app ; \
                      echo "Deploying to Production" ; \
                      docker-compose --profile prod down -v ; \
                      docker compose --profile prod pull ; \
                      docker compose --profile prod up -d --force-recreate'