name: Build and Deploy to Azure VM

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ "main" ]
  tags:
    - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Step 2: Debug environment
    - name: Debug environment
      run: |
        echo "GitHub Ref: ${{ github.ref }}"
        echo "GitHub SHA: ${{ github.sha }}"
        echo "Working Directory: $(pwd)"
        ls -la
    
    # Step 3: Docker Hub Login
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Step 4: Debug Docker Info
    - name: Debug Docker
      run: |
        docker info
        docker version
        echo "Current Docker images:"
        docker images
    
    # Step 5: Build and Push Docker Image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: oranmz/app:latest,oranmz/app:${{ github.sha }}
    
    # Step 6: Verify Docker Image
    - name: Verify Docker Image
      run: |
        echo "Verifying pushed images..."
        docker pull oranmz/app:latest
        docker images | grep oranmz/app
    
    # Step 7: Test SSH Connection
    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        script: |
          echo "SSH Connection Successful"
          whoami
          pwd
          docker --version
          docker-compose --version
    
    # Step 8: Deploy to Azure VM
    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        script: |
          echo "Starting deployment..."
          cd testing
          pwd
          echo "Current directory contents:"
          ls -la
          echo "Pulling latest Docker images..."
          docker-compose pull
          echo "Starting containers..."
          docker-compose up -d
          echo "Checking container status..."
          docker ps
          echo "Deployment complete"

    # Step 9: Verify Deployment
    - name: Verify Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        script: |
          echo "Verifying deployment..."
          cd testing
          docker-compose ps
          docker logs $(docker-compose ps -q) --tail 50