name: Deploy to Dev/Staging

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed
    branches:
      - dev
      - staging

env:
  IMAGE_NAME: oranmz/app

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure VM
        run: |
          az vm run-command invoke \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_VM_NAME }} \
            --command-id RunShellScript \
            --scripts 'cd /home/ISadmin/app ; \
                      echo "Deploying to ${{ env.DEPLOY_ENV }}" ; \
                      docker-compose --profile ${{ env.DEPLOY_ENV }} down -v ; \
                      docker-compose --profile ${{ env.DEPLOY_ENV }} pull ; \
                      docker-compose --profile ${{ env.DEPLOY_ENV }} up -d --force-recreate'
