name: Build and Deploy to Azure VM

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ "main" ]
  tags:
    - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: oranmz/app:latest,oranmz/app:${{ github.sha }}
        
    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}  # Using password authentication
        script: |
          cd testing
          docker-compose pull
          docker-compose up -d