# .github/workflows/docker-build.yml
name: Build Docker Image

on:
  push:
    branches:
      - dev
      - staging
    tags:
      - 'v*'
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment and version
        id: env_vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_EVENT_NAME == pull_request ]]; then
            LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            VERSION=$(echo $LAST_TAG | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          else
            BRANCH=${GITHUB_REF#refs/heads/}
            echo "ENV=$BRANCH" >> $GITHUB_ENV
            VERSION=$(echo $GITHUB_REF_NAME | grep -Eo '[0-9]+.[0-9]+.[0-9]+' || echo "0.0.0")
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT


      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}  # Only push latest on main
            type=raw,value=${{ env.ENV }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}