name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Push to Local Registry
        run: |
          echo "Logging into registry..."
          echo "123123" | docker login 10.0.3.6:5000 -u oran --password-stdin
          echo "Building image..."
          docker build -t 10.0.3.6:5000/testenv:${{ github.sha }} .
          echo "Pushing to local registry..."
          docker push 10.0.3.6:5000/testenv:${{ github.sha }}
      
      - name: Deploy to Local
        run: |
          echo "Logging into registry..."
          echo "123123" | docker login 10.0.3.6:5000 -u oran --password-stdin
          echo "Pull the image"
          docker pull 10.0.3.6:5000/testenv:${{ github.sha }}
        
      - name : Deploy to vm2
        run: |
          echo "SSH into vm2 and pull image"
          ssh -i ~/.ssh/github_runner 10.0.3.5 "echo '123123' | docker login 10.0.3.6:5000 -u oran --password-stdin && \
                        docker pull 10.0.3.6:5000/testenv:${{ github.sha }} && \
                        docker stop testenv || true && \
                        docker rm testenv || true && \
                        docker run -d --name testenv 10.0.3.6:5000/testenv:${{ github.sha }}"