# .github/workflows/docker-build.yml
name: Build Docker Image

on:
  push:
    branches:
      - dev
      - staging
    tags:
      - 'v*'
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment and version
        id: env_vars
        run: |
          # Get the last tag version
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0")
          # Get major.minor version only (e.g., 1.0)
          BASE_VERSION=$(echo $LAST_TAG | sed 's/v//' | awk -F. '{print $1"."$2}')
          
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Production release with tag
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            # Branch build or PR - use shorter version with run number
            VERSION="$BASE_VERSION.${GITHUB_RUN_NUMBER}"
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest,enable=${{ github.event.pull_request.merged == true }}
            type=raw,value=${{ github.ref_name }},enable=${{ !startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}