# .github/workflows/docker-build.yml
name: Build Docker Image

on:
  push:
    branches:
      - dev
      - staging
    tags:
      - 'v*'
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version
        id: version
        run: |
          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
            VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            MAJOR=$(echo $VERSION | cut -d. -f1 | tr -d 'v')
            VERSION="v$((MAJOR+1)).0.0"
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            VERSION="${GITHUB_REF#refs/heads/}-$SHORT_SHA"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/app
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=${{ github.ref_name }},enable=${{ github.ref_type == 'branch' }}
            type=sha,prefix=${{ github.ref_name }}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}